### PR TITLE
Add nuvoton 482 usb fs platform

### PR DESCRIPTION
**Pull request by frmdstryr**
This is a copy of the m484 platform modified to use the USB FS peripheral.

I tested it with a M482ZE8AE and was able to successfully flash an m252 series using pyocd.

Other than a few differences in main.c and usb_m482.c it is mostly the same as the m484 so it could be merged into that platform if you would prefer that. 

Please review if you have time and thank you for sharing your work.  P.S. this is one of the cleanest code bases I have ever worked with :)

### CODE REVIEW

**Comment by ataradov** [comment]
I will not be merging this. I only add platforms that I personally have and the ones that have potential wide interest to others.

The primary goal of this project is the DAP part itself. platforms are just basic reference code. I'm considering dropping SAM D21 and SAM E70 support too. The first one is very similar to SAM D11, which I primarily use for FS stuff. And the second one was added because of the HS support, but with M484 I don't need it and I don't think anyone else uses it either.

I'm always on a lookout for interesting HS devices, but for FS I see no point in Nuvoton devices, there are lots of decent FS devices.

I had a quick look at the code, and DAP_CONFIG_PACKET_SIZE must match USB_DAP_EP_SIZE and for FS it can't be bigger than 64. You have DAP_CONFIG_PACKET_SIZE set to 512, and this is why you had to add that multi-frame receive in the USB driver, which is also not something drivers should do.

**Comment by frmdstryr** [comment]
No worries, thanks for the feedback!

I noticed while playing with this that pyocd's gdb server for remote debugging didnt work.  Is that unrelated to dap or just not implemented?

**Comment by ataradov** [comment]
This project implements everything that is necessary for the DAP protocol. The rest is on the host software. So, it would be on the pyocd side.

**Comment by frmdstryr** [comment]
After correcting the config size and reverting the multi-frame receive it's now working fine with gdb. Thanks again!

**Pull request closed without merging**
